### ISSUE TITLE
Can Cocopods be supported?

### ISSUE THREAD

**Issue by devchena** [nohype-ai/SwiftObserver#5]
Thank you.

**Comment by flowtoolz** [comment]
Of course, it can technically be supported.

But I dropped support long ago since the present and future of Swift dependency management clearly is the [Swift Package Manager](https://github.com/apple/swift-package-manager).

So I won't invest time in maintaining legacy Cocoapods support or even finding out how to automate that.

There exist platforms to discover Swift packages:

* https://swiftpackageregistry.com
* https://swiftpackageindex.com

And the infrastructure for hosting Swift package registries is also growing:

* [Package Registry Service (implemented since Swift 5.7)](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md)
* [GitHub Registry Support](https://github.blog/2019-06-03-github-package-registry-will-support-swift-packages/)

I'm curious: Do you have technical or other reasons that prevent you from using Swift packages?

**Comment by devchena** [comment]
Thanks for your reply. At present, we use more Cocoapods.
